id: AA744A64F
title: Prayer for the Long Life of Lochen Ngawang Chöpal
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:14:19.463220
  last_modified_at: 2022-02-28 23:14:19.463226
