id: AA744A64F
title: A Short Practice for Averting Obstacles through Vajrakīla
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:14:19.456964
  last_modified_at: 2022-02-28 23:14:19.456970
