id: AA744A64F
title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:14:19.461279
  last_modified_at: 2022-02-28 23:14:19.461285
